<ReaderPage>:
    name: 'reader_page'

    BoxLayout:
        orientation: 'vertical'

        ScrollView:
            id: content_scroll
            do_scroll_x: False
            do_scroll_y: True

            Label:
                id: content
                padding: 12, 12
                size_hint_y: None
                height: self.texture_size[1]
                text_size: root.width, None

        BottomControlBar:
